### ISSUE TITLE
Panic on nats-pub

### ISSUE THREAD

**Issue by aricart** [nats-io/go-nats#311]
Got a crasher here - in the scenario I was changing server permissions, and using the client to publish a message. Filing an issue so that we have a look and not loose the panic.

```
[~]$ nats-pub -s tls://test:test@n0:10994 hello.hi bar
Published [hello.hi] : 'bar'
[~]$ nats-pub -s tls://test:test@n0:10994 bye.foo foo
nats: permissions violation for publish to "bye.foo"
[~]$ nats-pub -s tls://test:test@n0:10994 hello.foo bar
Segmentation fault: 11
[~]$ nats-pub -s tls://test:test@n0:10994 hello.foo bar
Published [hello.foo] : 'bar'
[~]$ nats-pub -s tls://test:test@n0:10994 hello.foo bar
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1048b]

runtime stack:
runtime.throw(0x389a20, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x4ae420)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x4ae420, 0x1, 0xd, 0x5ac548)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff618)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x4ae420, 0x1, 0x1000000000d, 0x1012f)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x4afca0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x4afca0, 0x5ac548)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x54f000, 0xd, 0x5ac548)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x4aab00)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:245 fp=0xc8200ce4b8 sp=0xc8200ce4b0
runtime.mallocgc(0xc0, 0x25b0c0, 0xcf5000d600000001, 0x21edf0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc8200ce590 sp=0xc8200ce4b8
runtime.newobject(0x25b0c0, 0xc1dbc700c153012c)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc8200ce5b8 sp=0xc8200ce590
crypto/elliptic.p256Inverse(0xc82038aca0, 0x4, 0x4, 0xc820309360, 0x4, 0x4)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/elliptic/p256_amd64.go:282 +0x2f fp=0xc8200ce6b8 sp=0xc8200ce5b8
crypto/elliptic.initTable()
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/elliptic/p256_amd64.go:402 +0x3d0 fp=0xc8200ce7f8 sp=0xc8200ce6b8
sync.(*Once).Do(0x4c5cb8, 0x3ac860)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/once.go:44 +0xe4 fp=0xc8200ce820 sp=0xc8200ce7f8
crypto/elliptic.(*p256Point).p256BaseMult(0xc820309260, 0xc8200ce930, 0x4, 0x4)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/elliptic/p256_amd64.go:422 +0x3b fp=0xc8200ce900 sp=0xc8200ce820
crypto/elliptic.p256Curve.ScalarBaseMult(0xc82012f240, 0xc82038ac80, 0x20, 0x20, 0xc8200ce9c8, 0x20)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/elliptic/p256_amd64.go:236 +0xd4 fp=0xc8200ce978 sp=0xc8200ce900
crypto/elliptic.GenerateKey(0x5a8970, 0xc82012f240, 0x5a3320, 0xc820016960, 0xc82038ac80, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/elliptic/elliptic.go:299 +0x2b4 fp=0xc8200ce9f0 sp=0xc8200ce978
crypto/tls.(*ecdheKeyAgreement).generateClientKeyExchange(0xc820372940, 0xc820092280, 0xc8200923c0, 0xc820087200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/key_agreement.go:388 +0x1ef fp=0xc8200ceb80 sp=0xc8200ce9f0
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc8200cf6a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/handshake_client.go:431 +0x121b fp=0xc8200cf238 sp=0xc8200ceb80
crypto/tls.(*Conn).clientHandshake(0xc8200b4000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/handshake_client.go:213 +0x1737 fp=0xc8200cf750 sp=0xc8200cf238
crypto/tls.(*Conn).Handshake(0xc8200b4000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/crypto/tls/conn.go:1033 +0xec fp=0xc8200cf790 sp=0xc8200cf750
github.com/nats-io/nats.(*Conn).makeTLSConn(0xc820031000)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:726 +0x24d fp=0xc8200cf878 sp=0xc8200cf790
github.com/nats-io/nats.(*Conn).checkForSecure(0xc820031000, 0x0, 0x0)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:901 +0xdc fp=0xc8200cf938 sp=0xc8200cf878
github.com/nats-io/nats.(*Conn).processExpectedInfo(0xc820031000, 0x0, 0x0)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:928 +0x17a fp=0xc8200cf9c0 sp=0xc8200cf938
github.com/nats-io/nats.(*Conn).processConnectInit(0xc820031000, 0x0, 0x0)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:819 +0x1c5 fp=0xc8200cfa70 sp=0xc8200cf9c0
github.com/nats-io/nats.(*Conn).connect(0xc820031000, 0x0, 0x0)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:855 +0x2d8 fp=0xc8200cfb68 sp=0xc8200cfa70
github.com/nats-io/nats.Options.Connect(0x0, 0x0, 0xc820012d80, 0x1, 0x1, 0x0, 0x3376f0, 0x8, 0x0, 0x0, ...)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:528 +0x19d fp=0xc8200cfc68 sp=0xc8200cfb68
github.com/nats-io/nats.Connect(0x7fff5fbff974, 0x36, 0xc8200cfdf0, 0x1, 0x1, 0xb, 0x0, 0x0)
	/Users/albertoricart/go/src/github.com/nats-io/nats/nats.go:301 +0x1cb fp=0xc8200cfd98 sp=0xc8200cfc68
main.main()
	/Users/albertoricart/go/src/github.com/nats-io/nats/examples/nats-pub.go:31 +0x210 fp=0xc8200cff30 sp=0xc8200cfd98
runtime.main()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8200cff80 sp=0xc8200cff30
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200cff88 sp=0xc8200cff80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1
[~]$ nats-pub -s tls://test:test@n0:10994 hello.foo bar
Published [hello.foo] : 'bar'
[~]$ nats-pub -s tls://test:test@n0:10994 hello.foo bar
Published [hello.foo] : 'bar'
[~]$ 

```

**Comment by kozlovic** [comment]
Please recompile with a more recent version that Go (trace shows 1.6.2) and see if you can reproduce.

**Comment by aricart** [comment]
I cannot reproduce it with a current build.
