### ISSUE TITLE
Reconnect failure under high load

### ISSUE THREAD

**Issue by lucwillems** [nats-io/go-nats#407]
i was testing/reviewing performance and stability of current java library. during this test i noticed that
in some cases, a disconnected consumer (disconnected by server because of slow consumer) was not able to reconnect because of following error :
```
13:05:41.997 [pool-4-thread-1] ERROR Listener - conn: receiver-1
java.io.IOException: Read channel closed.
	at io.nats.client.impl.NatsConnectionReader.run(NatsConnectionReader.java:138)
	at java.lang.Thread.run(Thread.java:748)
13:05:41.997 [pool-4-thread-1] INFO Listener - conn: receiver-1  event=nats: connection disconnected
13:05:43.741 [sender-0  ] INFO Main - sender  : 551439 msg/sec CONNECTED
13:05:44.017 [pool-4-thread-1] ERROR Listener - conn: receiver-1
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:319)
	at io.nats.client.impl.NatsConnection.reconnect(NatsConnection.java:225)
	at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:471)
	at io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:428)
	at java.lang.Thread.run(Thread.java:748)
```
- the receiver connection sees the disconnect, and starts the reconnect 
- during reconnect we get TimeoutException , and after this , ALL reconnect attemps fail with this error.

i'm using :
- docker nats server version 1.3.0
- java 8 / nats library 2.3.0

i have a small test application which produces this error after some time.
see https://github.com/lucwillems/nats-stability

a workaround is to call   connection.close() in the error Listener class , but this has ofcourse
some other major drawback that we need to create a new Connection instance and manage all subscriptions outside the Connection class.

**Comment by lucwillems** [comment]
oeps was closed unwanted

**Comment by kozlovic** [comment]
Seem that you are using the Java client, you probably should have created it in that repo, no?

**Comment by wallyqs** [comment]
Btw transferring issues among repos in Github is in beta now: https://help.github.com/articles/transferring-an-issue-to-another-repository/
